import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Commercial Pro privacy policy — how we collect, use, and protect your information.",
};

export default function PrivacyPage() {
  return (
    <main>
      <div className="legal-hero grid-bg">
        <div className="hero-accent-bar" />
        <div className="legal-hero-inner">
          <div className="section-tag" style={{ color: "var(--accent)" }}>
            Legal
          </div>
          <h1 className="legal-h1">
            Privacy <em>Policy</em>
          </h1>
          <p className="legal-lead">
            Last updated: April 2026 · Commercial Pro is committed to protecting your privacy and handling your data responsibly.
          </p>
        </div>
      </div>

      <div className="legal-body">
        <div className="legal-section">
          <h2>Information We Collect</h2>
          <p>
            When you use Commercial Pro&apos;s AI quoting platform, we collect information you provide directly, including business name, property
            address, vehicle details, driver information, and coverage preferences. We also collect usage data including pages visited, features used,
            and quote history.
          </p>
          <p>
            We do not collect Social Security numbers, payment card numbers (handled by Stripe), or personal financial account information through our
            platform forms.
          </p>
        </div>
        <div className="legal-section">
          <h2>How We Use Your Information</h2>
          <ul>
            <li>To generate insurance quotes and connect you with carrier markets</li>
            <li>To improve the accuracy of our AI underwriting models</li>
            <li>To communicate with you about your account and submissions</li>
            <li>To comply with legal and regulatory obligations</li>
            <li>To detect and prevent fraud or misuse of the platform</li>
          </ul>
        </div>
        <div className="legal-section">
          <h2>Information Sharing</h2>
          <p>
            We share your submission data with insurance carriers and MGAs for the purpose of generating quotes. We do not sell your personal
            information to third parties for marketing purposes. We may share data with service providers who assist in platform operations (hosting,
            analytics, payment processing) under strict confidentiality agreements.
          </p>
          <p>
            We may disclose information when required by law, regulation, or legal process, or to protect the rights and safety of our users and the
            public.
          </p>
        </div>
        <div className="legal-section">
          <h2>AI-Generated Quotes — Important Disclosure</h2>
          <p>
            The quotes generated by our AI agent are illustrative estimates based on self-reported information and AI-modeled underwriting assumptions.
            They are not binding insurance offers and do not guarantee coverage availability or final pricing. All coverage is subject to full
            underwriting review and carrier approval.
          </p>
          <p>
            Commercial Pro operates as a licensed insurance platform. Coverage is placed through licensed producers in applicable states. AI-generated
            outputs should not be construed as professional insurance advice.
          </p>
        </div>
        <div className="legal-section">
          <h2>Data Security</h2>
          <p>
            We use industry-standard encryption (TLS/SSL) for all data transmission. Our infrastructure is hosted on SOC 2 compliant platforms. Access
            to client data is restricted to authorized personnel only. We conduct regular security reviews and maintain incident response procedures.
          </p>
        </div>
        <div className="legal-section">
          <h2>Data Retention</h2>
          <p>
            We retain quote and submission data for a minimum of 5 years to comply with insurance regulatory requirements. You may request deletion of
            your account data by contacting us at info@commercialpro.ai, subject to applicable legal retention requirements.
          </p>
        </div>
        <div className="legal-section">
          <h2>Your Rights</h2>
          <p>
            Depending on your state of residence, you may have rights to access, correct, delete, or restrict processing of your personal information.
            California residents have additional rights under CCPA. To exercise these rights, contact us at info@commercialpro.ai or (973) 307-7007.
          </p>
        </div>
        <div className="legal-section">
          <h2>Contact Us</h2>
          <p>For privacy questions or to exercise your data rights:</p>
          <p>
            <strong>Commercial Pro</strong>
            <br />
            Email:{" "}
            <a href="mailto:info@commercialpro.ai" style={{ color: "var(--accent)" }}>
              info@commercialpro.ai
            </a>
            <br />
            Phone:{" "}
            <a href="tel:9733077007" style={{ color: "var(--accent)" }}>
              (973) 307-7007
            </a>
          </p>
        </div>
      </div>
    </main>
  );
}
